"""qwer12241231

Revision ID: 06db0deaead3
Revises: 534a6085c046
Create Date: 2024-02-24 17:44:52.266970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06db0deaead3'
down_revision: Union[str, None] = '534a6085c046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_group_user_id_key', 'user_group', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_group_user_id_key', 'user_group', ['user_id'])
    # ### end Alembic commands ###
