"""qwer122

Revision ID: 39d927cc05fb
Revises: c538a4fd0ef8
Create Date: 2024-02-24 17:37:49.614297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d927cc05fb'
down_revision: Union[str, None] = 'c538a4fd0ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'address', ['id'])
    op.create_unique_constraint(None, 'group', ['id'])
    op.drop_constraint('group_user_id_fkey', 'group', type_='foreignkey')
    op.drop_column('group', 'user_id')
    op.create_unique_constraint(None, 'profile', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user_group', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_group', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'profile', type_='unique')
    op.add_column('group', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('group_user_id_fkey', 'group', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'group', type_='unique')
    op.drop_constraint(None, 'address', type_='unique')
    # ### end Alembic commands ###
