"""2231qwer1224123121312

Revision ID: 7a0c6002df95
Revises: 93c1228b5009
Create Date: 2024-02-24 17:54:08.590170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0c6002df95'
down_revision: Union[str, None] = '93c1228b5009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_group', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint('unique_for_user_one_unique_group', 'user_group', ['user_id', 'group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_for_user_one_unique_group', 'user_group', type_='unique')
    op.alter_column('user_group', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
